version: '3'

includes:
  analytics-service:
    taskfile: ./Taskfile.service.yaml
    vars:
      SRC_ROOT: ./shopping-analytics-service
  cart-service:
    taskfile: ./Taskfile.service.yaml
    vars:
      SRC_ROOT: ./shopping-cart-service
  order-service:
    taskfile: ./Taskfile.service.yaml
    vars:
      SRC_ROOT: ./shopping-order-service

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  set-context:
    cmds:
      - kubectl config use-context docker-desktop
    silent: true
  deploy:
    cmds:
      - task: set-context
      - kubectl apply -k ./etc/k8s
    silent: true
  destroy:
    cmds:
      - task: set-context
      - kubectl delete -k ./etc/k8s
    silent: true