version: '3.9'
services:

  cart-service1:
    image: shopping-cart-service:latest
    hostname: cart-service1
    ports:
      - "8101:8101"
    networks:
      - sandbox

  cart-service2:
    image: shopping-cart-service:latest
    hostname: cart-service2
    ports:
      - "8102:8101"
    networks:
      - sandbox

  cart-service3:
    image: shopping-cart-service:latest
    hostname: cart-service3
    ports:
      - "8103:8101"
    networks:
      - sandbox

volumes: {}

networks:
  sandbox:
    name: sandbox-net