version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready"
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./ddl-scripts/01_create_akka_tables.sql
        target: /docker-entrypoint-initdb.d/01_create_akka_tables.sql
        read_only: true
      - type: bind
        source: ./ddl-scripts/02_create_user_tables.sql
        target: /docker-entrypoint-initdb.d/02_create_user_tables.sql
        read_only: true
    environment:
      POSTGRES_USER: shopping-cart
      POSTGRES_PASSWORD: shopping-cart

  kafka:
    image: docker.io/bitnami/kafka:3.7
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

volumes:
  db_data:
  kafka_data:
