apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - releaseName: metrics-server
            serverUrl: https://kubernetes.default.svc
            namespace: kube-system
            chart: metrics-server
            repoURL: https://kubernetes-sigs.github.io/metrics-server/
            targetRevision: 3.12.1
          - releaseName: keda
            serverUrl: https://kubernetes.default.svc
            namespace: keda-system
            chart: keda
            repoURL: https://kedacore.github.io/charts
            targetRevision: 2.13.2
          - releaseName: external-secrets
            serverUrl: https://kubernetes.default.svc
            namespace: external-secrets
            chart: external-secrets
            repoURL: https://charts.external-secrets.io
            targetRevision: 0.1.1
          - releaseName: istio-base
            serverUrl: https://kubernetes.default.svc
            namespace: istio-system
            chart: base
            repoURL: https://istio-release.storage.googleapis.com/charts
            targetRevision: 1.21.0-rc.0
          - releaseName: istio-istiod
            serverUrl: https://kubernetes.default.svc
            namespace: istio-system
            chart: istiod
            repoURL: https://istio-release.storage.googleapis.com/charts
            targetRevision: 1.21.0-rc.0
          - releaseName: istio-ingressgateway
            serverUrl: https://kubernetes.default.svc
            namespace: istio-system
            chart: gateway
            repoURL: https://istio-release.storage.googleapis.com/charts
            targetRevision: 1.21.0-rc.0
          - releaseName: docker-registry
            serverUrl: https://kubernetes.default.svc
            namespace: docker-registry
            chart: docker-registry
            repoURL: https://helm.twun.io
            targetRevision: 2.2.2
  template:
    metadata:
      name: '{{chart}}'
    spec:
      project: default
      sources:
        - chart: '{{chart}}'
          repoURL: '{{repoURL}}'
          targetRevision: '{{targetRevision}}'
          helm:
            releaseName: '{{ .releaseName }}'
            valueFiles:
              - '$values/{{ .releaseName }}.yaml'
        - repoURL: 'https://github.com/semusings/akka-shopping-cart-microservices.git'
          targetRevision: 'main'
          path: 'k8s/values'
          ref: values
      destination:
        server: '{{serverUrl}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - PruneLast=true
          - ServerSideApply=true
          - Validate=true
          - Replace=true
        retry:
          limit: 30
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s