apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - releaseName: cart-service
            serverUrl: https://kubernetes.default.svc
            namespace: cart-service
            chart: x-app
            repoURL: https://github.com/semusings/k8s-apps.git
            targetRevision: main
          - releaseName: analytics-service
            serverUrl: https://kubernetes.default.svc
            namespace: analytics-service
            chart: x-app
            repoURL: https://github.com/semusings/k8s-apps.git
            targetRevision: main
          - releaseName: order-service
            serverUrl: https://kubernetes.default.svc
            namespace: order-service
            chart: x-app
            repoURL: https://github.com/semusings/k8s-apps.git
            targetRevision: main
  template:
    metadata:
      name: '{{chart}}'
    spec:
      project: default
      sources:
        - path: 'charts/{{ .chart }}'
          repoURL: '{{repoURL}}'
          targetRevision: '{{targetRevision}}'
          helm:
            releaseName: '{{ .releaseName }}'
            valueFiles:
              - '$values/k8s/values/{{ .releaseName }}.yaml'
        - repoURL: 'https://github.com/semusings/akka-shopping-cart-microservices.git'
          targetRevision: 'main'
          ref: values
      destination:
        server: '{{serverUrl}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - PruneLast=true
          - ServerSideApply=true
          - Validate=true
          - Replace=true
        retry:
          limit: 30
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s