---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: k8s-system
spec:
  selector:
    app: postgresql-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgresql-service
  name: postgresql-service
  namespace: k8s-system
spec:
  serviceName: postgresql-service
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-service
  template:
    metadata:
      labels:
        app: postgresql-service
    spec:
      containers:
        - name: postgresql-service
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: "shopping-cart"
            - name: POSTGRES_USER
              value: "shopping-cart"
            - name: POSTGRES_PASSWORD
              value: "shopping-cart"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-service-data
            - mountPath: /docker-entrypoint-initdb.d/
              name: postgresql-service-ddl-scripts
      volumes:
        - name: postgresql-service-data
          persistentVolumeClaim:
            claimName: postgresql-service-data
        - name: postgresql-service-ddl-scripts
          configMap:
            name: postgresql-service-ddl-scripts
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-service-data
  namespace: k8s-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi