{{- $configMapData := .Values.configData }}
{{- $appName := .Values.conf.appName }}
{{- $configMapName := .Values.conf.configMapName }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ $appName | quote }}
  name: {{ $configMapName | quote }}
data:
  {{- range $k, $v := $configMapData }}
  {{ $k }}: {{ $v }}
  {{- end}}