{{- if .Values.externalSecret.enabled }}
{{- $externalSecret := .Values.externalSecret }}
{{- $appName := .Values.conf.appName }}
{{- $secretName := .Values.conf.secretName }}
{{- $namespace := .Release.Namespace }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  labels:
    app: {{ $appName | quote }}
  name: {{ $secretName | quote }}
spec:
  refreshInterval: {{ default "15s" ($externalSecret).refreshInterval | quote }}
  secretStoreRef:
    name: {{ ($externalSecret).storeName | quote }}
    kind: {{ ($externalSecret).storeKind | quote }}
  target:
    name: {{ $secretName | quote }}
  data:
    {{- range ($externalSecret).data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRefKey }}
        {{- if .remoteRefProperty }}
        property: {{ .remoteRefProperty }}
        {{- end }}
    {{- end }}
{{- end }}