{{- $appName := .Values.conf.appName }}
{{- $serviceAccountName := .Values.conf.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName | quote }}
  labels:
    app: {{ $appName | quote }}