{{- if .Values.istio.enabled }}
{{- $istioGateway := .Values.istio.gateway }}
{{- $host := .Values.istio.host }}
{{- $appName := .Values.conf.appName }}
{{- $serviceName := .Values.conf.serviceName }}
{{- $namespace := .Release.Namespace }}
{{- $servicePort := 80 }}
{{- $uriPrefix := default "/" .Values.istio.uriPrefix }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $serviceName | quote }}
spec:
  hosts:
    - {{ $host | quote }}
  gateways:
    - {{ $istioGateway | quote }}
  http:
    - match:
        - uri:
            prefix: {{ $uriPrefix | quote }}
      route:
        - destination:
            port:
              number: {{ $servicePort }}
            host:  {{ printf "%s.%s.svc.cluster.local" $serviceName $namespace | quote }}
{{- end }}